### ISSUE TITLE
Implement setting: exclude if declared above

### ISSUE THREAD

**Issue by zardoy** [maIIady/vscode-tailwind-in-css#1]
Will be enabled by default.
Exclude *rule* if its body is met above. We should check every rule for now.

Example:

```scss
div {
    float: left;
    float-left // shouldn't be suggested if setting is enabled
}
```
